### ISSUE TITLE
Ability to Zoom in on Timeline to See Audio Gaps in Long Videos

### ISSUE THREAD

**Issue by chrusher** [dbvideostriketeam/wubloader#251] opened 2021-11-13 11:29 UTC
In long videos (such as Zeta Shift discussion videos, a one second gap in the audio can only be one pixel. It would be useful if you could zoom in the timeline to more easily place the cut.

**Comment by ekimekim** [comment] 2024-03-09 19:58
duplicate of https://github.com/dbvideostriketeam/wubloader/issues/381

**Closed by ekimekim** 2024-03-09 19:58 UTC
Labels: P4 - Ideas, C - Thrimbletrimmer
