### ISSUE TITLE
Seperate Upload Location and Cut Type in Thrimbletrimmer

### ISSUE THREAD

**Issue by chrusher** [dbvideostriketeam/wubloader#446] opened 2024-11-03 20:37 UTC
Currently upload locations and cut types are mixed together in the `Upload Location` dropdown in Advanced Submission Options. Upload location and cut types should be separate dropdowns.

**Comment by dcollinsn** [comment] 2024-11-03 20:41
Dupe of #431?

**Comment by ekimekim** [comment] 2024-11-03 21:06
Technically that's about the backend and this is UI for the same, but yes it should just be one issue.

**Closed by ekimekim** 2024-11-03 21:06 UTC
Labels: P3 - Nice to Have, C - Thrimbletrimmer
